export const themePresets = {
  default: {
    primaryColor: '#8b5cf6',
    accentColor: '#14b8a6',
    backgroundColor: '#ffffff',
    textColor: '#171717',
    fontFamily: 'geist',
    cardStyle: 'default',
    animation: 'fade',
    borderRadius: 'rounded',
    shadows: true,
    glassmorphism: false,
  },
  cyberpunk: {
    primaryColor: '#f0f',
    accentColor: '#0ff',
    backgroundColor: '#000',
    textColor: '#fff',
    fontFamily: 'mono',
    cardStyle: 'glassmorphism',
    animation: 'slide',
    borderRadius: 'sharp',
    shadows: true,
    glassmorphism: true,
    backgroundOverlay: 'rgba(255,0,255,0.1)',
  },
  minimal: {
    primaryColor: '#000',
    accentColor: '#666',
    backgroundColor: '#fff',
    textColor: '#000',
    fontFamily: 'geist',
    cardStyle: 'default',
    animation: 'fade',
    borderRadius: 'pill',
    shadows: false,
    glassmorphism: false,
  },
} as const 